[project]
name = "cpu-ml-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.9.0",
    "icecream>=2.1.8",
    "pydantic>=2.11.9",
    "pydantic-settings>=2.10.1",
    "pylint>=3.3.8",
]
