name: Back End Build

on:
  workflow_call:
    inputs:
      python_version:
        description: 'Python version'
        required: true
        type: string
        default: '3.13'
  push:
    branches-ignore:
      - main

jobs:
  API-Build-And-Test:
    env:
      python_version: ${{ inputs.python_version }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python_version }}

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install dependencies
        run: |
          uv sync --frozen

      - name: Run Python isort
        run: |
          uv run isort ./src

      - name: Run Python black
        run: |
          uv run black --check --verbose ./src

      - name: Analysing the code with pylint
        run: |
          uv run pylint --rcfile=.pylintrc $(git ls-files '**/*.py')

      - name: Test with pytest
        run: |
          uv run pytest pytests
